export default {
  name: "Alimentos",
  icon: "/assets/icons/alimentos.svg",
  words: [
    "abacate",
    "abacaxi",
    "abiu",
    "abobrinha",
    "abrico",
    "abobora",
    "abobora jacarezinho",
    "acaraje",
    "acelga",
    "acerola",
    "achocolatado",
    "adocante",
    "agriao",
    "aguardente",
    "aipim",
    "aipo",
    "alcachofra",
    "alcaparra",
    "alecrim",
    "alface",
    "alfajor",
    "algodao doce",
    "alho",
    "alho-poro",
    "almeirao",
    "almondega",
    "alpiste",
    "amaranto",
    "ambrosia",
    "ameixa",
    "amendoim",
    "amido de milho",
    "amora",
    "amendoa",
    "angu",
    "araca",
    "arroz",
    "arroz doce",
    "arroz integral",
    "arroz tropeiro",
    "asa de frango",
    "aspargo",
    "atemoia",
    "aveia",
    "avela",
    "azeite",
    "azeite de dende",
    "azeitona",
    "azeitona preta",
    "acafrao",
    "acai",
    "acucar",
    "acucar mascavo",
    "baba de moca",
    "bacalhau",
    "bacon",
    "bacuri",
    "baguete",
    "bala",
    "bala de coco",
    "bala de goma",
    "banana",
    "banana split",
    "banana-da-terra",
    "banana-maca",
    "banana-nanica",
    "banana-prata",
    "bananada",
    "barra de cereais",
    "batata",
    "batata baroa",
    "batata frita",
    "batata palha",
    "batata-doce",
    "batida",
    "baunilha",
    "bauru",
    "beijinho",
    "beirute",
    "bengala doce",
    "berinjela",
    "bertalha",
    "beterraba",
    "bife",
    "bife a milanesa",
    "bife a parmegiana",
    "biscoito",
    "biscoito da sorte",
    "bisteca",
    "bobo de camarao",
    "bolacha",
    "bolinho de arroz",
    "bolinho de bacalhau",
    "bolinho de chuva",
    "bolo",
    "bolo de abacaxi",
    "bolo de aipim",
    "bolo de aniversario",
    "bolo de brigadeiro",
    "bolo de cafe",
    "bolo de caju",
    "bolo de caja",
    "bolo de cenoura",
    "bolo de chocolate",
    "bolo de coco",
    "bolo de fuba",
    "bolo de kiwi",
    "bolo de laranja",
    "bolo de leite",
    "bolo de limao",
    "bolo de maracuja",
    "bolo de morango",
    "bolo de sorvete",
    "bolo formigueiro",
    "bolo marmore",
    "bombom",
    "brevidade",
    "brigadeiro",
    "brioche",
    "broa",
    "broto de feijao",
    "brocolis",
    "burritos",
    "cabelo de anjo",
    "cacau",
    "cachaca",
    "cachorro quente",
    "cafe",
    "cafe com leite",
    "caipirinha",
    "cajamanga",
    "caju",
    "cajuzinho",
    "caja",
    "calabresa",
    "caldo de cana",
    "caldo de carne",
    "caldo de galinha",
    "caldo de mocoto",
    "caldo verde",
    "caldo-de-feijao",
    "camarao empanado",
    "cambuca",
    "camu-camu",
    "cana-de-acucar",
    "canape",
    "canela",
    "canelone",
    "canja de galinha",
    "canjica",
    "capelete",
    "capim santo",
    "cappuccino",
    "caqui",
    "carambola",
    "caramelo",
    "carne",
    "carne de sol",
    "carne moida",
    "caruru",
    "casadinho",
    "casquinha",
    "casquinha de siri",
    "castanha",
    "caviar",
    "cebola",
    "cebola empanada",
    "cebola roxa",
    "cebolinha",
    "cenoura",
    "cereal",
    "cereja",
    "cerveja",
    "champanhe",
    "champignon",
    "chantilly",
    "charque",
    "cheddar",
    "cheesecake",
    "cheiro verde",
    "chester",
    "chiclete",
    "chicoria",
    "chimarrao",
    "chimichurri",
    "chocolate",
    "chocolate amargo",
    "chocolate branco",
    "chocolate granulado",
    "chocolate quente",
    "chocotone",
    "chopp",
    "chuchu",
    "chucrute",
    "churrasco",
    "churros",
    "cha",
    "cha de boldo",
    "cha de camomila",
    "cha de hortela",
    "cha gelado",
    "cha mate",
    "cha preto",
    "cha verde",
    "cidra",
    "clara",
    "cocada",
    "cocada preta",
    "coco",
    "coco ralado",
    "coentro",
    "cogumelo",
    "colorau",
    "cominho",
    "conhaque",
    "contra file",
    "cookies",
    "coracao de frango",
    "coracao de galinha",
    "costela",
    "couve",
    "couve-de-bruxelas",
    "couve-flor",
    "coxa de frango",
    "coxinha",
    "cozido",
    "cravo",
    "creme de abobora",
    "creme de avela",
    "creme de leite",
    "creme de milho",
    "crepe",
    "croissant",
    "croquete",
    "cupcake",
    "cupuacu",
    "curau",
    "curry",
    "cuscuz",
    "damasco",
    "dobradinha",
    "doce de abacaxi",
    "doce de abobora",
    "doce de banana",
    "doce de caju",
    "doce de coco",
    "doce de figo",
    "doce de jaca",
    "doce de kiwi",
    "doce de leite",
    "doce de mamao",
    "doce de manga",
    "doce de morango",
    "doce de pessego",
    "empada",
    "empadao",
    "endivia",
    "energetico",
    "erva-doce",
    "ervilha",
    "escargot",
    "escarola",
    "esfirra",
    "espaguete",
    "espetinho",
    "espinafre",
    "farinha",
    "farofa",
    "feijoada",
    "feijao",
    "feijao azuki",
    "feijao branco",
    "feijao fradinho",
    "feijao manteiga",
    "feijao preto",
    "fermento",
    "figo",
    "file",
    "file mignon",
    "flan",
    "fogazza",
    "fondue",
    "framboesa",
    "frango",
    "frango empanado",
    "frango a parmegiana",
    "frango a passarinho",
    "frango-xadrez",
    "fruta-do-conde",
    "fruta-pao",
    "fuba",
    "funghi",
    "gabiroba",
    "ganache",
    "garapa",
    "gelatina",
    "gelatina de morango",
    "geleia",
    "gema",
    "gengibre",
    "gergelim",
    "glace",
    "goiaba",
    "goiabada",
    "gorgonzola",
    "granola",
    "graviola",
    "groselha",
    "grumixama",
    "grao de bico",
    "guacamole",
    "guandu",
    "guarana",
    "hamburguer",
    "hortela",
    "hostia",
    "inga",
    "inhame",
    "iogurte",
    "jabuticaba",
    "jaca",
    "jambo",
    "jamelao",
    "jatai",
    "jatoba",
    "jenipapo",
    "jerimum",
    "jilo",
    "jujuba",
    "kafta",
    "ketchup",
    "kiwi",
    "laranja",
    "lasanha",
    "leite",
    "leite condensado",
    "leite de coco",
    "leite de soja",
    "leite em po",
    "lentilha",
    "lichia",
    "licor",
    "lima",
    "limonada",
    "limao",
    "linguica",
    "linhaca",
    "lombo",
    "louro",
    "macadamia",
    "macarronada",
    "macarrao",
    "macarrao instantaneo",
    "maionese",
    "maisena",
    "malagueta",
    "mamao",
    "mandioca",
    "mandioquinha",
    "manga",
    "mangaba",
    "mangostao",
    "manjar",
    "manjericao",
    "manteiga",
    "maracuja",
    "margarina",
    "maria mole",
    "marisco",
    "marmelada",
    "marmelo",
    "marshmallow",
    "mate",
    "maxixe",
    "maca",
    "maca do amor",
    "maca verde",
    "mel",
    "melancia",
    "melao",
    "menta",
    "merengue",
    "mexerica",
    "milho",
    "milkshake",
    "mingau",
    "mirtilo",
    "misto quente",
    "molho agridoce",
    "molho barbecue",
    "molho branco",
    "molho de pimenta",
    "molho de tomate",
    "molho ingles",
    "molho madeira",
    "molho rose",
    "molho shoyu",
    "molho tartaro",
    "moranga",
    "morango",
    "mortadela",
    "mostarda",
    "mousse",
    "mousse de chocolate",
    "mousse de limao",
    "mousse de maracuja",
    "mousse de morango",
    "muffin",
    "muqueca",
    "murici",
    "mucarela",
    "musculo",
    "nabo",
    "nachos",
    "nectarina",
    "nhoque",
    "noz-moscada",
    "nozes",
    "nuggets",
    "nespera",
    "olho de sogra",
    "omelete",
    "orobo",
    "oregano",
    "ovo",
    "ovo de codorna",
    "ovo de pascoa",
    "palha italiana",
    "palmito",
    "pamonha",
    "panetone",
    "panqueca",
    "papo de anjo",
    "parmesao",
    "pasta de amendoim",
    "pastel",
    "pastel de belem",
    "pastilha",
    "pate",
    "pave",
    "pacoca",
    "peito de frango",
    "peito de peru",
    "pepino",
    "pepperoni",
    "pequi",
    "pera",
    "pernil",
    "petit gateau",
    "petit suisse",
    "picanha",
    "picles",
    "picole",
    "pimenta",
    "pimenta do reino",
    "pimentao",
    "pinha",
    "pinhao",
    "pipoca",
    "pipoca doce",
    "pirulito",
    "pirao",
    "pistache",
    "pitanga",
    "pitaya",
    "pitomba",
    "pizza",
    "polenta",
    "polvilho",
    "presunto",
    "profiteroles",
    "provolone",
    "pudim",
    "pudim de pao",
    "pure",
    "pao",
    "pao australiano",
    "pao de alho",
    "pao de batata",
    "pao de forma",
    "pao de lo",
    "pao de mel",
    "pao de queijo",
    "pao doce",
    "pao frances",
    "pao integral",
    "pao sirio",
    "pe de galinha",
    "pe-de-moleque",
    "pessego",
    "queijadinha",
    "queijo",
    "queijo ralado",
    "quentao",
    "quiabo",
    "quibe",
    "quindim",
    "quinoa",
    "rabada",
    "rabanada",
    "rabanete",
    "rapadura",
    "ravioli",
    "racao",
    "refrigerante",
    "repolho",
    "repolho roxo",
    "requeijao",
    "ricota",
    "risoles",
    "risoto",
    "rocambole",
    "rolinho primavera",
    "roma",
    "rondele",
    "rosbife",
    "rosquinha",
    "rum",
    "rucula",
    "sagu",
    "sal",
    "sal grosso",
    "salada",
    "salada de frutas",
    "salame",
    "salgadinho",
    "salpicao",
    "salsa",
    "salsicha",
    "salsao",
    "sanduiche",
    "sapoti",
    "saque",
    "sarapatel",
    "sashimi",
    "sequilho",
    "siriguela",
    "soja",
    "sonho",
    "sopa",
    "sopa de legumes",
    "sorvete",
    "sorvete napolitano",
    "strogonoff",
    "suco",
    "suco de abacaxi",
    "suco de acerola",
    "suco de goiaba",
    "suco de graviola",
    "suco de laranja",
    "suco de limao",
    "suco de maracuja",
    "suco de maca",
    "suco de morango",
    "suco de pitanga",
    "suco de uva",
    "sufle",
    "sundae",
    "sushi",
    "suspiro",
    "tacaca",
    "taco",
    "talharim",
    "tamarindo",
    "tangerina",
    "tapioca",
    "temaki",
    "tequila",
    "tiramisu",
    "tofu",
    "tomate",
    "tomate cereja",
    "tomate seco",
    "tomilho",
    "toranja",
    "torrada",
    "torresmo",
    "torrone",
    "torta",
    "torta alema",
    "torta de limao",
    "torta de maracuja",
    "torta de pessego",
    "tortilha",
    "trigo",
    "trufa",
    "tucupi",
    "tamara",
    "umbu",
    "urucum",
    "uva",
    "uva passa",
    "uisque",
    "vaca atolada",
    "vagem",
    "vatapa",
    "vinagre",
    "vinagrete",
    "vinho",
    "vinho branco",
    "vitamina",
    "vodca",
    "waffles",
    "wasabi",
    "yakisoba",
    "agua",
    "agua com gas",
    "agua de coco",
    "oleo",
    "sidra",
    "pe de moleque",
    "banana vermelha",
  ],
};
