export default {
  name: "Desenhos",
  icon: "/assets/icons/desenhos.svg",
  words: [
    "2 cachorros bobos",
    "a bruxinha sabrina",
    "a casa do mickey mouse",
    "a casa monstro",
    "a familia addams",
    "a familia camundongo",
    "a hora do recreio",
    "a nova escola do imperador",
    "a pantera cor-de-rosa",
    "a pequena sereia",
    "a turma do bairro",
    "a vaca e o frango",
    "a vida moderna de rocko",
    "aang",
    "adolepeixes",
    "adao leao",
    "agumon",
    "aizen sousuke",
    "ajudante de papai noel",
    "akamaru",
    "aladin",
    "amy",
    "ana pimentinha",
    "androide 18",
    "andy panda",
    "angel beats",
    "animaniacs",
    "anpanman",
    "apenas um show",
    "aqua teen",
    "aquaman",
    "ariel",
    "arlequina",
    "arqueiro verde",
    "as aventuras de babar",
    "as aventuras de jackie chan",
    "as aventuras de tintim",
    "as meninas superpoderosas",
    "as mumias vivas",
    "as super gatinhas",
    "as trapalhadas de flapjack",
    "as trigemeas",
    "astro boy",
    "avatar",
    "aventuras com os kratts",
    "baby looney tunes",
    "babao",
    "bacamarte e chumbinho",
    "backyardigans",
    "bakugan",
    "bambam",
    "bananaman",
    "barbapapa",
    "barbie",
    "bardock",
    "barney",
    "bart",
    "batatinha",
    "batfino e karate",
    "batgirl",
    "batman",
    "beavis and butt-head",
    "ben 10",
    "bender",
    "bernardo e bianca",
    "betty atomica",
    "betty boop",
    "beyblade",
    "bibo pai e bobi filho",
    "bicudo, o lobisomem",
    "billy",
    "bisonho",
    "bleach",
    "bloo",
    "bob esponja",
    "bob o construtor",
    "bojack horseman",
    "bolinha",
    "bonkers",
    "bosko",
    "bouli",
    "brandy e sr bigodes",
    "brasinhas do espaco",
    "bratz",
    "breadwinners",
    "brutus",
    "bucky",
    "buffy a caca-vampiros",
    "bumblebee",
    "buzz lightyear",
    "caillou",
    "canario negro",
    "capitao america",
    "capitao caverna",
    "capitao falange",
    "capitao planeta",
    "carangos e motocas",
    "carmen sandiego",
    "carnage",
    "cascao",
    "cat noir",
    "catatau",
    "catdog",
    "cavalo de fogo",
    "caverna do dragao",
    "caverninha",
    "caca-fantasmas",
    "cebolinha",
    "centurions",
    "charley e mimmo",
    "charlie brown",
    "charlie e lola",
    "chaves",
    "cheetara",
    "chi chi",
    "chico bento",
    "chilly willy",
    "chowder",
    "ciclope",
    "cinderela",
    "clarabela",
    "clarencio, o otimista",
    "clifford",
    "coelho osvaldo",
    "coelho ricochete",
    "coragem, o cao covarde",
    "coracao gelado",
    "coringa",
    "corrida alucinante",
    "corrida maluca",
    "cosmo",
    "costelinha",
    "cowboy bebop",
    "cowboys de moo mesa",
    "coyote",
    "cruella",
    "cyberchase",
    "cyborg 009",
    "danny phantom",
    "daphne blake",
    "darkwing duck",
    "darwin",
    "dave, o barbaro",
    "death note",
    "dee dee",
    "deidara",
    "dennis, o pimentinha",
    "dick vigarista",
    "digimon",
    "dino",
    "dinosaucers",
    "dipper pines",
    "distroller",
    "docinho",
    "dodoria",
    "doki",
    "dom pixote",
    "dora, a aventureira",
    "doraemon",
    "doug",
    "doutora brinquedos",
    "draculaura",
    "dragon ball",
    "dragon quest fly",
    "droopy",
    "du, dudu e edu",
    "duck dodgers",
    "ducktales",
    "duelo xiaolin",
    "duende verde",
    "dumbo",
    "edward elric",
    "eek the cat",
    "eric cartman",
    "erza",
    "escola pra cachorro",
    "esquadrilha abutre",
    "esquilo sem grilo",
    "eu sou o maximo",
    "eufrazino",
    "eustacio bagge",
    "ever after high",
    "fairy tail",
    "family guy",
    "familia dracula",
    "familia urso",
    "fanboy e chum chum",
    "fate stay night",
    "faisca e fumaca",
    "felicia",
    "finn",
    "flapjack",
    "flash",
    "flash gordon",
    "floquinho",
    "florzinha",
    "fly",
    "formiga atomica ",
    "frajola",
    "frajuto",
    "frangolino",
    "franjinha",
    "freakazoid",
    "fred flintstone",
    "freeza",
    "frozen",
    "fullmetal alchemist",
    "futurama",
    "fuzzy confusao",
    "gaara",
    "gaguinho",
    "galaxy trio",
    "galinha pintadinha",
    "gambit",
    "garfield",
    "garnet",
    "garu",
    "gary",
    "gasparzinho ",
    "gato corajoso",
    "gato felix",
    "george, o rei da floresta",
    "ghoulia yelps",
    "glub-glub",
    "godzilla",
    "gogeta",
    "gohan",
    "goku",
    "gormiti",
    "gorpo",
    "goten",
    "gravity falls",
    "gumball",
    "gargulas",
    "hamtaro",
    "happy tree friends",
    "harry e o balde de dinossauros",
    "he-man",
    "hellsing",
    "hey arnold",
    "hi hi puffy amiyumi",
    "historinhas de dragoes",
    "homem de ferro",
    "homem passaro",
    "homem-aranha",
    "homer",
    "hong kong fu",
    "hora de aventura",
    "hortelino",
    "hulk",
    "hunter x hunter",
    "ikki",
    "ilha dos desafios",
    "inspetor bugiganga",
    "inuyasha",
    "invasor zim",
    "irmao do jorel",
    "irmaos metralha",
    "itachi",
    "jade chan",
    "jake",
    "jake long",
    "jaken",
    "jambo e ruivao",
    "jaspion",
    "jay jay, o jatinho",
    "jean grey",
    "jessica rabbit",
    "jim no mundo da lua",
    "jimbo",
    "jimmy neutron",
    "jiraiya",
    "johnny bravo",
    "johnny test",
    "jonny quest",
    "jorgen von estranho",
    "josie e as gatinhas",
    "joao grandao",
    "juanito jones",
    "juggernaut",
    "juniper lee",
    "kagome",
    "kakashi",
    "katara",
    "ken",
    "kevin levin",
    "kiara",
    "kiba",
    "kick buttowski",
    "kid flash",
    "kid vs. kat",
    "killer bee",
    "kim possible",
    "kissyfur",
    "konan",
    "korra",
    "kovu",
    "krypto",
    "kuririn",
    "lagoona blue",
    "lanterna verde",
    "lapis lazuli",
    "leitao",
    "lex luthor",
    "leao da montanha",
    "leoncio",
    "liga da justica",
    "ligeirinho",
    "lilica",
    "lilo e stitch",
    "lindinha",
    "lion-o",
    "lisa",
    "lola bunny",
    "lola e virginia",
    "lucky star",
    "luffy",
    "lula lele",
    "lula molusco",
    "luluzinha",
    "mabel pines",
    "macaco loco",
    "madeline",
    "magali",
    "maggie",
    "magneto",
    "maguila, o gorila",
    "majin boo",
    "manda chuva",
    "mandark",
    "mandy",
    "mansao foster para amigos imaginarios",
    "marcelino pao e vinho",
    "marge",
    "marsupilami",
    "martin mystery",
    "marvin, o marciano",
    "masha e o urso",
    "max",
    "max steel",
    "meany ranheta",
    "mecanimais",
    "medabots",
    "megaman",
    "megas xlr",
    "mestre dos magos",
    "mestre kame",
    "mestre karin",
    "mestre splinter ",
    "meu amigo da escola e um macaco",
    "mickey mouse",
    "mike, lu e og",
    "miles do amanha",
    "milhouse",
    "minato",
    "minions",
    "minnie mouse",
    "mirai nikki",
    "miss spider",
    "mistureba",
    "moby dick",
    "mona a vampiro",
    "monkey d luffy",
    "monster high",
    "monster rancher",
    "moranguinho",
    "mordecai",
    "mosquito, mosquete e moscardo",
    "mr. Magoo",
    "mr. satan",
    "mucha lucha",
    "mulher gato",
    "mulher gaviao",
    "mulher invisivel",
    "muppet babies",
    "muriel",
    "mutano",
    "mutante rex",
    "muttley",
    "my little pony",
    "monica",
    "musculo total",
    "nami",
    "nanatsu no taizai",
    "naruto",
    "natsu",
    "ned flanders",
    "nermal",
    "nossa turma",
    "noturno",
    "o acampamento de lazlo",
    "o cachorro vira-lata",
    "o clube das winx",
    "o coisa",
    "o demolidor",
    "o estranho mundo de jack",
    "o fantastico mundo de bobby",
    "o grande polegar",
    "o incrivel mundo de gumball",
    "o justiceiro",
    "o laboratorio de dexter",
    "o mascara",
    "o patinho duque",
    "o pequeno urso",
    "o pequeno vampiro",
    "o poderoso hercules",
    "o quarteto fantastico",
    "o urso do cabelo duro",
    "o vale dos dinossauros",
    "odie",
    "olaf",
    "olho vivo e faro fino",
    "olivia palito",
    "one piece",
    "one punch-man",
    "orochimaru",
    "os 6 bionicos",
    "os anjinhos",
    "os camundongos aventureiros",
    "os castores pirados",
    "os cavaleiros do zodiaco",
    "os caezinhos do canil",
    "os defensores da terra",
    "os flintstones",
    "os herculoides",
    "os impossiveis",
    "os incriveis",
    "os jetsons",
    "os jovens titas",
    "os jovens titas em acao",
    "os meninos desordeiros",
    "os mussarelas",
    "os oblongs",
    "os padrinhos magicos",
    "os pinguins de madagascar",
    "os sete monstrinhos",
    "os simpsons",
    "os smurfs",
    "os snorks",
    "os substitutos",
    "os super patos",
    "os sabados secretos",
    "os thornberrys",
    "os vingadores",
    "pairulito",
    "papa-leguas",
    "papai sabe nada",
    "pateta",
    "pato donald",
    "patolino",
    "patrick",
    "patrulha canina",
    "paty maionese",
    "pedrita",
    "peixonauta",
    "penelope pussycat",
    "penelope charmosa",
    "pepe le gamba",
    "pepe legal",
    "peppa pig",
    "peridot",
    "pernalonga",
    "perninha",
    "perry o ornitorrinco",
    "pete puma",
    "peter griffin",
    "peter pan",
    "peter perfeito",
    "peter potamus",
    "phineas e ferb",
    "pica-pau",
    "piccolo",
    "piggley winks",
    "pingu",
    "pinky dinky doo",
    "pinky e o cerebro",
    "piu-piu",
    "pixcodelics",
    "planet survival",
    "planeta sheen",
    "plankton",
    "plic, ploc e chuvisco",
    "plucky",
    "pluto",
    "pocoyo",
    "pokemon",
    "pole position",
    "polly pocket",
    "popeye",
    "presto",
    "presuntinho",
    "princesa caroco",
    "princesa jujuba",
    "princesas-do-mar",
    "princesinha sofia",
    "professor dingle dong",
    "professor utonio",
    "projeto zeta",
    "pucca",
    "puro osso",
    "pe de pano",
    "perola sirigueijo",
    "quadrilha de morte",
    "quatro bracos",
    "ranma",
    "rato minuto",
    "ravena",
    "recruta zero",
    "redakai",
    "rick e morty",
    "rigby",
    "riquinho rico",
    "robin",
    "robot boy",
    "rock lee",
    "rocket power",
    "roy corroi",
    "rupert",
    "ryu",
    "saga de gemeos",
    "sagwa",
    "sailor moon",
    "saitama",
    "sakura card captors",
    "sakura kinomoto",
    "samurai champloo",
    "samurai jack",
    "samurai x",
    "sandy bochechas",
    "sanjay e craig",
    "sanji",
    "saori",
    "sasuke",
    "scooby-doo",
    "se liga ian",
    "seiya",
    "shaman king",
    "shazam",
    "she-ra",
    "sheep na cidade grande",
    "shenlong",
    "shikamaru",
    "shin chan",
    "shino",
    "shinzo",
    "show da luna",
    "shura de capricornio",
    "shurato",
    "silverhawks",
    "simba",
    "sininho",
    "snoopy",
    "sokka",
    "sonic",
    "south park",
    "space ghost",
    "spawn",
    "speed racer",
    "spiff e hercules",
    "sr sirigueijo",
    "sr. Burns",
    "sr. sinistro",
    "stan smith",
    "star vs as forcas do mal",
    "steven universe",
    "stewie",
    "super campeoes",
    "super choque",
    "super dinamo",
    "super esquadrao dos macacos robos",
    "super homem",
    "super onze",
    "super pig",
    "super sumo",
    "super vaca",
    "superamigos",
    "supernoobs",
    "surfista prateado",
    "swat kats",
    "tartaruga touche",
    "tartarugas ninja",
    "tarzan",
    "taz",
    "temari",
    "tempestade",
    "tenchi muyo",
    "terk",
    "the tick",
    "thomas e seus amigos",
    "thor",
    "thundercats",
    "tico e teco",
    "tigrao",
    "timmy turner",
    "timao e pumba",
    "tiny toon",
    "tio chan",
    "tio patinhas",
    "titio avo",
    "tobi",
    "tocha humana",
    "tom e jerry",
    "totoro",
    "transformers",
    "trigun",
    "trunks",
    "tres espias demais",
    "tsuna",
    "tsunade senju",
    "tutubarao",
    "turma da monica",
    "twf",
    "ulquiorra",
    "uma robo adolescente",
    "ursinho pooh",
    "ursinhos carinhosos",
    "ursinhos gummy",
    "valentino troca-tapa",
    "vampira",
    "vash",
    "vegeta",
    "velma",
    "venom",
    "vingador",
    "vinicius e tom",
    "vovo uranai",
    "w.i.t.c.h.",
    "wally gator",
    "wanda",
    "wilma",
    "woodstock",
    "woody",
    "x-men",
    "xavier",
    "yin yang yo!",
    "yu yu hakusho",
    "yu-gi-oh!",
    "yumi",
    "yzma",
    "zatch bell",
    "zeca urubu",
    "zero no tsukaima",
    "zuko",
    "zurg",
    "ze carioca",
    "ze colmeia",
    "ze jacare",
  ],
};
