export default {
  name: "Filmes",
  icon: "/assets/icons/filmes.svg",
  words: [
    "007",
    "13 fantasmas",
    "2 filhos de francisco",
    "2001 uma odisseia no espaco",
    "300",
    "7 caixas",
    "a arca de noe",
    "a bailarina",
    "a barraca do beijo",
    "a batalha de riddick",
    "a bela e a fera",
    "a bolha assassina",
    "a bruxa de blair",
    "a bussola de ouro",
    "a cadeira do diabo",
    "a caixa",
    "a casa amaldicoada",
    "a casa caiu",
    "a casa da colina",
    "a casa das coelhinhas",
    "a casa de cera",
    "a casa de vidro",
    "a casa do lago",
    "a casa dos espiritos",
    "a casa dos passaros mortos",
    "a chave mestra",
    "a chave magica",
    "a chegada",
    "a coisa",
    "a colheita do mal",
    "a conquista da honra",
    "a conquista do paraiso",
    "a cor de um crime",
    "a cor purpura",
    "a corrente do bem",
    "a corrente do mal",
    "a creche do papai",
    "a culpa e das estrelas",
    "a dama de ferro",
    "a dama dourada",
    "a dama oculta",
    "a enfermeira betty",
    "a era do gelo",
    "a escola de susto do gasparzinho",
    "a esfera",
    "a espia",
    "a estrada",
    "a estrada da vida",
    "a experiencia",
    "a familia da noiva",
    "a familia do futuro",
    "a fantastica fabrica de chocolate",
    "a feiticeira",
    "a filha do presidente",
    "a forma da agua",
    "a freira",
    "a fuga das galinhas",
    "a garota da capa vermelha",
    "a garota dinamarquesa",
    "a hora de voltar",
    "a hora do pesadelo",
    "a hora do rush",
    "a ilha",
    "a invasao",
    "a invasao das aranhas gigantes",
    "a lagoa azul",
    "a lenda do cavaleiro sem cabeca",
    "a lenda do tesouro perdido",
    "a lenda do zorro",
    "a lenda dos guardioes",
    "a liga extraordinaria",
    "a lista de schindler",
    "a luta pela esperanca",
    "a menina e o cavalo",
    "a mentira",
    "a morte lhe cai bem",
    "a morte pede carona",
    "a morte te da parabens",
    "a mulher de preto",
    "a mulher invisivel",
    "a mascara do zorro",
    "a mao assassina",
    "a mao que balanca o berco",
    "a mumia",
    "a noite do jogo",
    "a noiva cadaver",
    "a noiva de chucky",
    "a nova cinderela",
    "a nova onda do imperador",
    "a novica rebelde",
    "a nevoa",
    "a origem",
    "a outra",
    "a paixao de cristo",
    "a praia",
    "a princesa prometida",
    "a profecia",
    "a proposta",
    "a rede social",
    "a rocha",
    "a sogra",
    "a sombra do guerreiro",
    "a sombra e a escuridao",
    "a setima alma",
    "a teoria de tudo",
    "a troca",
    "a viagem de chihiro",
    "a vida nao e um sonho",
    "a vida secreta das abelhas",
    "a vila",
    "a volta do todo poderoso",
    "a volta dos mortos vivos",
    "a ultima musica",
    "a ultima sessao de cinema",
    "abismo do medo",
    "abracadabra",
    "abril despedacado",
    "abril sangrento",
    "acampamento do papai",
    "ace ventura",
    "adeus, lenin!",
    "advogado do diabo",
    "agora voce ve",
    "aladdin",
    "alguem tem que ceder",
    "alice no pais das maravilhas",
    "alien vs predador",
    "almas condenadas",
    "alone in the dark",
    "alvin e os esquilos",
    "alem da vida",
    "american pie",
    "amigas para sempre",
    "amizade colorida",
    "amor alem da vida",
    "amor sem escalas",
    "anaconda",
    "animais fantasticos e onde habitam",
    "anjo maldito",
    "anjos da lei",
    "anjos da noite",
    "anjos da vida",
    "anjos do sol",
    "anjos e demonios",
    "annabelle",
    "antes do amanhecer",
    "antes que termine o dia",
    "ao entardecer",
    "apocalypto",
    "apollo 13",
    "apos a morte",
    "aquamarine",
    "aracnofobia",
    "armageddon",
    "arquivo-x",
    "arraste-me para o inferno",
    "as aventuras de pi",
    "as branquelas",
    "as bruxas de salem",
    "as cronicas de narnia",
    "as cronicas de spiderwick",
    "as invasoes barbaras",
    "as loucuras de dick e jane",
    "as mumias do farao",
    "as panteras",
    "as patricinhas de beverly hills",
    "as tartarugas ninjas",
    "assalto sobre trilhos",
    "atividade paranormal",
    "atos que desafiam a morte",
    "ate a morte",
    "ate que a sorte nos separe",
    "avatar",
    "azul e a cor mais quente",
    "bad boys",
    "bambi",
    "bandidas",
    "barry e a banda das minhocas",
    "bastardos inglorios",
    "bater ou correr",
    "batismo de sangue",
    "batman o cavaleiro das trevas",
    "battle royale",
    "bebes geniais",
    "bee movie",
    "beethoven",
    "beijo do dragao",
    "beleza americana",
    "bem-vindo a selva",
    "bicho de sete cabecas",
    "bird box",
    "birdman",
    "blade o cacador de vampiros",
    "blade runner",
    "bob esponja o filme",
    "bonequinha de luxo",
    "branca de neve e o cacador",
    "brinquedo assassino",
    "cabo do medo",
    "cadaveres",
    "cade a minha entrega?",
    "caminhando nas nuvens",
    "camp rock",
    "canguru jack",
    "cantando na chuva",
    "capitao america",
    "carandiru",
    "carga explosiva",
    "carros",
    "carruagens de fogo",
    "cartas na mesa",
    "cartas para julieta",
    "casa de areia",
    "casablanca",
    "casamento grego",
    "cassino",
    "cassino royale",
    "cacadores de mentes",
    "central do brasil",
    "chicago",
    "chuva negra",
    "cidade de deus",
    "cidade dos anjos",
    "cidade dos homens",
    "cidade dos sonhos",
    "cidades de papel",
    "cidadao kane",
    "cinema paradiso",
    "cinema, aspirinas e urubus",
    "cinquenta tons de cinza",
    "cisne negro",
    "click",
    "closer",
    "clube da luta",
    "comando para matar",
    "como caes e gatos",
    "como se fosse a primeira vez",
    "como treinar o seu dragao",
    "constantine",
    "conversando com deus",
    "coraline e o mundo secreto",
    "coracao de dragao",
    "coracao de tinta",
    "coracao louco",
    "coracao satanico",
    "coracao valente",
    "corrida da morte",
    "corrida mortal",
    "cowboys and aliens",
    "cowboys do espaco",
    "crash",
    "crepusculo",
    "crimes no paraiso",
    "curtindo a vida adoidado",
    "curvas perigosas",
    "caes assassinos",
    "caes de aluguel",
    "cao de briga",
    "circulo de fogo",
    "codigo de honra",
    "danca com lobos",
    "danca dos mortos",
    "dancando no escuro",
    "dancando para a vida",
    "de olhos bem fechados",
    "de pernas pro ar",
    "de repente e amor",
    "de volta para o futuro",
    "de volta a lagoa azul",
    "deja vu",
    "demolidor",
    "desafiando gigantes",
    "descendentes",
    "desejo proibido",
    "destinos ligados",
    "detona ralph",
    "deu a louca na chapeuzinho",
    "deu a louca na cinderela",
    "deus e brasileiro",
    "dia dos namorados macabro",
    "diamante de sangue",
    "dirty dance",
    "divergente",
    "divertidamente",
    "diva",
    "diario de um banana",
    "diario de uma paixao",
    "diarios de motocicleta",
    "django",
    "do comeco ao fim",
    "do que as mulheres gostam",
    "do que os homens gostam",
    "doces encontros",
    "dona flor e seus dois maridos",
    "donnie darko",
    "dormindo com o inimigo",
    "dormindo fora de casa",
    "doze homens e outro segredo",
    "doze e demais",
    "dragonball evolution",
    "dragao vermelho",
    "duro de matar",
    "e o vento levou",
    "e se fosse verdade",
    "e.t.",
    "eclipse mortal",
    "edward maos de tesoura",
    "efeito borboleta",
    "efeito domino",
    "ela",
    "ela e os caras",
    "ela e o cara",
    "ele nao esta tao afim de voce",
    "elektra",
    "embriagado de amor",
    "emoji",
    "encontro explosivo",
    "enrolados",
    "enterrado vivo",
    "entrando numa fria",
    "entre abelhas",
    "entre o ceu e a terra",
    "entre os muros da prisao",
    "entrevista com o vampiro",
    "era uma vez em hollywood",
    "era uma vez no oeste",
    "escola de rock",
    "escorpioes a bordo",
    "esporte sangrento",
    "espiritos",
    "esqueceram de mim",
    "eu os declaro marido e larry",
    "eu robo",
    "eu sou a lenda",
    "eu, eu mesmo e irene",
    "evidencias de um crime",
    "evocando espiritos",
    "extraordinario",
    "fale com ela",
    "fantasmas nunca dormem",
    "filadelfia",
    "filha da luz",
    "fim dos tempos",
    "fique rico ou morra tentando",
    "floresta do mal",
    "fome animal",
    "fomos herois",
    "fonte da vida",
    "formiguinhaz",
    "forrest gump",
    "free willy",
    "frozen",
    "ferias frustradas",
    "furia de titas",
    "gangues de nova york",
    "garfield",
    "garganta do diabo",
    "garota interrompida",
    "garotas rebeldes",
    "gente grande",
    "ghost do outro lado da vida",
    "gosto de sangue",
    "gravidade",
    "green book",
    "gremlins",
    "guerra ao terror",
    "guerra dos mundos",
    "guerra nas estrelas",
    "genio indomavel",
    "habitantes da escuridao",
    "hairspray",
    "halloween - a noite do terror",
    "hancock",
    "hannibal",
    "harry potter",
    "hellboy",
    "hellraiser",
    "high school musical",
    "highlander",
    "historia sem fim",
    "hitch conselheiro amoroso",
    "homem de ferro",
    "homem-formiga",
    "homens de honra",
    "homens em furia",
    "homens, mulheres e filhos",
    "hop rebelde sem pascoa",
    "hora de voltar",
    "hotel transilvania",
    "hulk",
    "identidade",
    "ilha do medo",
    "impacto profundo",
    "imperio do sol",
    "imperio dos lobos",
    "incontrolavel",
    "independence day",
    "indiana jones",
    "inimigos publicos",
    "instinto selvagem",
    "inteligencia artificial",
    "interestelar",
    "janela da alma",
    "janela indiscreta",
    "janela secreta",
    "jogador numero 1",
    "jogo de amor em las vegas",
    "jogo do amor",
    "jogo entre ladroes",
    "jogos mortais",
    "jogos vorazes",
    "johnny e june",
    "jornada nas estrelas",
    "jovem demais para morrer",
    "joao e maria cacadores de bruxas",
    "jumanji",
    "jumper",
    "juno",
    "jurassic park",
    "justica a qualquer preco",
    "justica de amor",
    "karate kid",
    "kill bill",
    "king kong",
    "king o rei da selva",
    "kung fu panda",
    "la la land",
    "ladrao de diamantes",
    "ladroes de bicicleta",
    "lanterna verde",
    "laranja mecanica",
    "legalmente loira",
    "lembrancas",
    "lenda urbana",
    "letra e musica",
    "leoes e cordeiros",
    "licenca para casar",
    "ligeiramente gravidos",
    "limite vertical",
    "lisbela e o prisioneiro",
    "logan",
    "lolita",
    "loucademia de policia",
    "lua nova",
    "lucy",
    "luzes da cidade",
    "lagrimas do sol",
    "mad max",
    "madagascar",
    "madrugada dos mortos",
    "madrugada muito louca",
    "magnolia",
    "mais estranho que a ficcao",
    "malditas aranhas",
    "malevola",
    "mamma mia",
    "mandando bala",
    "mar de fogo",
    "marido por acaso",
    "marley e eu",
    "marte ataca!",
    "mato sem cachorro",
    "matrix",
    "max payne",
    "medo do escuro",
    "megamente",
    "meia-noite em paris",
    "menina de ouro",
    "meninas malvadas",
    "menino maluquinho",
    "mensagem para voce",
    "meu malvado favorito",
    "meu primeiro amor",
    "meu primeiro homem",
    "meu tio matou um cara",
    "meus 15 anos",
    "mib homens de preto",
    "minha filha quer casar",
    "minha mae e uma peca",
    "minha super ex-namorada",
    "minhas maes e meu pai",
    "minions",
    "miss simpatia",
    "missao impossivel",
    "moana um mar de aventuras",
    "monstros s.a.",
    "moonlight",
    "moonwalker",
    "morangos silvestres",
    "mortal kombat",
    "morte negra",
    "motoqueiro fantasma",
    "moulin rouge",
    "mulan",
    "mulher-gato",
    "maquina mortifera",
    "na natureza selvagem",
    "na trilha da fama",
    "nasce uma estrela",
    "navio fantasma",
    "nem que a vaca tussa",
    "nine",
    "no cair da noite",
    "no pique de nova iorque",
    "no rastro da bala",
    "noite infernal",
    "noiva em fuga",
    "noivas em guerra",
    "norbit",
    "nosferatu",
    "noe",
    "naufrago",
    "o agente teen",
    "o albergue",
    "o amor e cego",
    "o ano em que faremos contato",
    "o aprendiz de feiticeiro",
    "o ataque dos tomates assassinos",
    "o auto da compadecida",
    "o aviador",
    "o balconista",
    "o bebe de rosemary",
    "o beijo da mulher-aranha",
    "o bem amado",
    "o bicho de sete cabecas",
    "o bicho vai pegar",
    "o caminho para casa",
    "o campeao",
    "o carro desgovernado",
    "o carteiro e o poeta",
    "o castelo animado",
    "o cacador de pipas",
    "o cacador e a rainha do gelo",
    "o cemiterio maldito",
    "o chamado",
    "o cheiro do ralo",
    "o cla das adagas voadoras",
    "o colecionador de ossos",
    "o corcunda de notre dame",
    "o corte",
    "o corvo",
    "o curioso caso de benjamin button",
    "o cao e a raposa",
    "o ceu pode esperar",
    "o codigo da vinci",
    "o despertar de uma paixao",
    "o dia depois de amanha",
    "o dia que a terra parou",
    "o diabo veste prada",
    "o ditador",
    "o diario da princesa",
    "o diario de uma baba",
    "o dorminhoco",
    "o dolar furado",
    "o equilibrista",
    "o escorpiao rei",
    "o escritor fantasma",
    "o espanta tubaroes",
    "o estranho mundo de jack",
    "o exorcismo de emily rose",
    "o exorcista",
    "o expresso polar",
    "o exterminador do futuro",
    "o fada do dente",
    "o fantasma da opera",
    "o fazendeiro de deus",
    "o filho de chucky",
    "o garoto",
    "o gato de botas",
    "o grande ditador",
    "o grande dragao branco",
    "o grinch",
    "o grito",
    "o guarda-costas",
    "o guia do mochileiro das galaxias",
    "o hobbit",
    "o homem bicentenario",
    "o homem da mascara de ferro",
    "o homem elefante",
    "o homem que copiava",
    "o homem que desafiou o diabo",
    "o homem sem sombra",
    "o iluminado",
    "o ilusionista",
    "o inferno de dante",
    "o invisivel",
    "o jardim secreto",
    "o jardineiro fiel",
    "o justiceiro",
    "o labirinto do fauno",
    "o lar das criancas peculiares",
    "o leitor",
    "o leopardo",
    "o livro de eli",
    "o lobisomem",
    "o lobo atras da porta",
    "o lutador",
    "o massacre da serra eletrica",
    "o menino da porteira",
    "o menino do pijama listrado",
    "o mentiroso",
    "o misterio das duas irmas",
    "o morro dos ventos uivantes",
    "o mundo de leland",
    "o magico de oz",
    "o maskara",
    "o nevoeiro",
    "o nome da rosa",
    "o orfanato",
    "o pagamento",
    "o pai da noiva",
    "o paizao",
    "o patriota",
    "o pentelho",
    "o pequenino",
    "o pequeno principe",
    "o pequeno stuart little",
    "o peste",
    "o pestinha",
    "o pianista",
    "o poderoso chefinho",
    "o poderoso chefao",
    "o procurado",
    "o professor aloprado",
    "o quarto do panico",
    "o quarto poder",
    "o rei leao",
    "o reino proibido",
    "o resgate do soldado ryan",
    "o retorno da mumia",
    "o segredo de brokeback mountain",
    "o senhor dos aneis",
    "o sexto sentido",
    "o show de truman",
    "o silencio dos inocentes",
    "o som do coracao",
    "o sotao",
    "o terminal",
    "o tigre e o dragao",
    "o vestido",
    "o vidente",
    "o vizinho",
    "o ultimo cacador de bruxas",
    "o ultimo dos moicanos",
    "o ultimo mestre do ar",
    "o ultimo portal",
    "o ultimo samurai",
    "o ultimo trem",
    "old boy",
    "olha quem esta falando",
    "olhar de anjo",
    "olhos famintos",
    "onde os fracos nao tem vez",
    "onde vivem os monstros",
    "onze homens e um segredo",
    "operacao big hero",
    "operacao cupido",
    "operacao valquiria",
    "os 101 dalmatas",
    "os batutinhas",
    "os caca-fantasmas",
    "os condenados",
    "os embalos de sabado a noite",
    "os infiltrados",
    "os mensageiros",
    "os mercenarios",
    "os normais",
    "os outros",
    "os pinguins do papai",
    "os produtores",
    "os passaros",
    "os reis da rua",
    "os seis signos da luz",
    "os sete samurais",
    "os simpsons",
    "os tres mosqueteiros",
    "os vingadores",
    "p.s. eu te amo",
    "paixao de aluguel",
    "pandorum",
    "paparazzi",
    "para sempre alice",
    "pele eterno",
    "pequenos espioes",
    "percy jackson",
    "perdido pra cachorro",
    "perfume de mulher",
    "peter pan",
    "pets a vida secreta dos bichos",
    "pinoquio",
    "piratas do caribe",
    "pixels",
    "planeta dos macacos",
    "planeta terror",
    "plano de voo",
    "pocahontas",
    "poder alem da vida",
    "por um fio",
    "porcos e diamantes",
    "preciosa",
    "predador",
    "premonicao",
    "prenda-me se for capaz",
    "pressagio",
    "procurando dory",
    "procurando nemo",
    "prometheus",
    "prova de fogo",
    "prologo dos ceus",
    "psicose",
    "pulp fiction",
    "panico",
    "panico a bordo",
    "panico na floresta",
    "panico no lago",
    "quando me apaixono",
    "quatro amigas e um jeans viajante",
    "quebrando a banca",
    "queime depois de ler",
    "quem quer ser um milionario?",
    "quem vai ficar com mary?",
    "rambo",
    "ratatouille",
    "ray",
    "resgate abaixo de zero",
    "resident evil",
    "rio",
    "rios vermelhos",
    "riquinho",
    "robin hood",
    "robocop",
    "rock star",
    "rocky",
    "roma",
    "s.o.s. do amor",
    "sangue negro",
    "santo matrimonio",
    "se beber, nao case!",
    "se ela danca eu danco",
    "se eu fosse voce",
    "sede de sangue",
    "seguranca de shopping",
    "sem novidade no front",
    "sem saida",
    "sempre ao seu lado",
    "senhores do crime",
    "separados pelo casamento",
    "serpentes a bordo",
    "sete vidas",
    "sexta-feira 13",
    "sexta-feira muito louca",
    "shakespeare apaixonado",
    "sherlock holmes",
    "shrek",
    "silencio dos inocentes",
    "sin city",
    "sinais",
    "sobre meninos e lobos",
    "sociedade dos poetas mortos",
    "soldado universal",
    "sorte no amor",
    "space jam",
    "sr. e sra. smith",
    "star trek",
    "star wars",
    "stardust",
    "stargate",
    "stigmata",
    "sukiyaki western django",
    "sweeney todd",
    "tapete vermelho",
    "taca de sangue",
    "ted",
    "temos vagas",
    "tempos modernos",
    "terror sobre rodas",
    "the notebook",
    "the wonders",
    "thor",
    "tinker bell",
    "tiros em ruanda",
    "titanic",
    "todo mundo em panico",
    "todo poderoso",
    "todos os caes merecem o ceu",
    "tomates verdes fritos",
    "top gun",
    "touro indomavel",
    "toy story",
    "trama internacional",
    "transformers",
    "tratamento de choque",
    "treinando o papai",
    "trolls",
    "tron",
    "tropa de elite",
    "troia",
    "turbo",
    "turistas",
    "ta chovendo hamburguer",
    "ta dando onda",
    "ta todo mundo louco",
    "ultravioleta",
    "um amor para recordar",
    "um corpo que cai",
    "um crime de mestre",
    "um dia de furia",
    "um doce olhar",
    "um estranho no ninho",
    "um faz de conta que acontece",
    "um homem serio",
    "um hotel bom pra cachorro",
    "um kickboxer muito louco",
    "um lobisomem americano em paris",
    "um olhar do paraiso",
    "um sonho de liberdade",
    "um sonho possivel",
    "um tira da pesada",
    "um tira no jardim de infancia",
    "uma aventura lego",
    "uma baba quase perfeita",
    "uma carta ao pai",
    "uma chamada perdida",
    "uma linda mulher",
    "uma mente brilhante",
    "uma noite alucinante",
    "uma noite magica",
    "uma noite no museu",
    "uma vida iluminada",
    "universidade monstros",
    "up altas aventuras",
    "v de vinganca",
    "vai que cola",
    "veia de lutador",
    "velocidade maxima",
    "velozes e furiosos",
    "vem dancar",
    "vem dancar comigo",
    "vestida para casar",
    "viagem ao centro da terra",
    "viagem maldita",
    "vida de inseto",
    "voando alto",
    "volcano",
    "voo noturno",
    "wall-e",
    "watchmen",
    "wifi ralph",
    "wolverine: imortal",
    "xuxa abracadabra",
    "xuxa e os duendes",
    "yeti",
    "zohan o agente bom de corte",
    "zootopia",
    "zumbilandia",
    "a espera de um milagre",
    "a procura da felicidade",
    "agua para elefantes",
    "e fada",
  ],
};
