export default {
  name: "Objetos",
  icon: "/assets/icons/objetos.svg",
  words: [
    "abafador",
    "abajur",
    "abotoadura",
    "abridor de garrafa",
    "abridor de latas",
    "adaga",
    "adaptador",
    "aerofolio",
    "afiador de facas",
    "agogo",
    "agulha",
    "agulha de croche",
    "agulheiro",
    "alargador",
    "alarme",
    "alaude",
    "aldrava",
    "alfinete",
    "algema",
    "algodao",
    "alianca",
    "alicate",
    "alicate de unha",
    "aljava",
    "almofada",
    "alto falante",
    "amortecedor",
    "ampulheta",
    "amuleto",
    "andador",
    "andaime",
    "anel",
    "aneleira",
    "anilha",
    "antena",
    "antena parabolica",
    "antolho",
    "anzol",
    "apagador",
    "aparador",
    "aparelho ortodontico",
    "apito",
    "apontador de lapis",
    "aquecedor",
    "aquario",
    "arame farpado",
    "arca",
    "arco",
    "armadilha",
    "armadura",
    "armario",
    "aro",
    "arpao",
    "asa delta",
    "aspersorio",
    "aspirador de po",
    "assadeira",
    "astrolabio",
    "autorama",
    "avental",
    "azulejo",
    "acucareiro",
    "bacia",
    "bafometro",
    "bagageiro",
    "baioneta",
    "balaclava",
    "balaio",
    "balanca",
    "balaustre",
    "balde",
    "baleiro",
    "balsa",
    "balao",
    "bambole",
    "banco",
    "bandana",
    "bandeira",
    "bandeja",
    "bandolim",
    "banheira",
    "banjo",
    "banqueta",
    "baqueta",
    "baralho",
    "barbante",
    "barbeador",
    "barraca",
    "barril",
    "basculante",
    "bastao",
    "bata",
    "batedeira",
    "batente",
    "bateria",
    "batina",
    "batom",
    "batuta",
    "bazuca",
    "bau",
    "beca",
    "beliche",
    "bengala",
    "berimbau",
    "bermuda",
    "berrante",
    "berco",
    "betoneira",
    "bicama",
    "bicho de pelucia",
    "bicicleta ergometrica",
    "bide",
    "bigorna",
    "bilboque",
    "bilhete",
    "binoculo",
    "biombo",
    "biqueira",
    "biquini",
    "biruta",
    "bisturi",
    "blusa",
    "boia",
    "boina",
    "bola",
    "bola de boliche",
    "bola de golfe",
    "bola de gude",
    "boleador",
    "bolero",
    "bolsa",
    "bolsa de palha",
    "bolsa termica",
    "bomba",
    "bomba de ar",
    "bombacha",
    "boneca",
    "bongo",
    "bone",
    "borracha",
    "borrifador",
    "bota",
    "botijao de gas",
    "botina",
    "botao",
    "boa",
    "bracelete",
    "brilho labial",
    "brinco",
    "brinquedo",
    "broca",
    "broche",
    "bronzeador",
    "bucha",
    "bule",
    "bumerangue",
    "buque",
    "burca",
    "bureta",
    "buzina",
    "biblia",
    "cabide",
    "cabideiro",
    "cabo",
    "cabresto",
    "cachecol",
    "cachepo",
    "cachimbo",
    "cadarco",
    "cadeado",
    "cadeira",
    "cadeira de balanco",
    "cadeira de praia",
    "cadeira de rodas",
    "cadeira eletrica",
    "caderneta",
    "caderno",
    "cafeteira",
    "caixa",
    "caixa de correio",
    "caixa de ferramentas",
    "caixa de fosforo",
    "caixa de isopor",
    "caixa de papelao",
    "caixa de som",
    "caixa registradora",
    "caixote",
    "caixao",
    "cajado",
    "calcinha",
    "caldeirao",
    "caleidoscopio",
    "calibrador",
    "calota",
    "calca",
    "calcadeira",
    "cama",
    "cama elastica",
    "camafeu",
    "camburao",
    "caminhao",
    "camisa",
    "camisa de forca",
    "camisa regata",
    "camiseta",
    "camisola",
    "canaleta",
    "candeeiro",
    "candelabro",
    "caneca",
    "caneleira",
    "caneta",
    "caneta hidrocor",
    "canga",
    "canivete",
    "cano",
    "canoa",
    "cantil",
    "cantoneira",
    "canudo",
    "capa",
    "capacete",
    "capacho",
    "capelo",
    "carimbo",
    "carpeta",
    "carregador de celular",
    "carretel",
    "carretilha",
    "carrilhao",
    "carrinho",
    "carrinho de bebe",
    "carrinho de feira",
    "carrinho de mao",
    "carrinho de rolima",
    "carta",
    "carteira",
    "cartola",
    "cartucho de tinta",
    "cartao",
    "cartao de credito",
    "cartao de memoria",
    "casaco",
    "cassetete",
    "castanholas",
    "castical",
    "casula",
    "cata-vento",
    "catapulta",
    "catraca",
    "cavalete",
    "cavalo de pau",
    "cavaquinho",
    "caxixi",
    "cacarola",
    "cd",
    "celada",
    "celular",
    "cerca eletrica",
    "ceroula",
    "cesta",
    "cetro",
    "chaleira",
    "chapinha de cabelo",
    "chapeu",
    "chapeu de aniversario",
    "charango",
    "charuto",
    "chave",
    "chave canhao",
    "chave de boca",
    "chave de fenda",
    "chave de grifo",
    "chave de roda",
    "chave estrela",
    "chave inglesa",
    "chaveiro",
    "chicote",
    "chimbal",
    "chinelo",
    "chip",
    "chocalho",
    "chupeta",
    "churrasqueira",
    "chuteira",
    "chuveiro",
    "cinta-liga",
    "cinto",
    "cinto de seguranca",
    "cinzel",
    "cisterna",
    "claquete",
    "clarinete",
    "clava",
    "clip",
    "coador",
    "cobertor",
    "cocar",
    "cofre",
    "coifa",
    "cola",
    "colar",
    "colcha",
    "colchonete",
    "colchao",
    "colchao inflavel",
    "coldre",
    "coleira",
    "colete",
    "colete cervical",
    "colher",
    "colher de pau",
    "colirio",
    "comedouro",
    "compasso",
    "computador",
    "concha",
    "conduite",
    "cone",
    "confete",
    "conga",
    "conta-gotas",
    "contrabaixo",
    "controle remoto",
    "convite",
    "copo",
    "coqueteleira",
    "corda",
    "corneta",
    "coroa",
    "corpete",
    "corrente",
    "corretivo",
    "corsario",
    "cortador de grama",
    "cortador de unha",
    "cortina",
    "cotoveleira",
    "coturno",
    "cracha",
    "criado-mudo",
    "cristal",
    "cristaleira",
    "crucifixo",
    "cruz",
    "cruzeta",
    "cubo magico",
    "cueca",
    "cuia",
    "curvador de cilios",
    "cutelo",
    "cuica",
    "calice",
    "cilios posticos",
    "comoda",
    "dado",
    "dardo",
    "dedal",
    "delineador",
    "depilador eletrico",
    "desentupidor",
    "desodorante",
    "despertador",
    "detector de fumaca",
    "detector de metais",
    "diamante",
    "dinamite",
    "disco",
    "disquete",
    "diva",
    "diario",
    "dobradica",
    "domino",
    "draga",
    "dvd",
    "echarpe",
    "edredom",
    "elmo",
    "elastico",
    "envelope",
    "enxada",
    "escada",
    "escalimetro",
    "escapamento",
    "escavadeira",
    "escopeta",
    "escorredor de macarrao",
    "escorredor de pratos",
    "escorregador",
    "escova",
    "escova de dente",
    "escrivaninha",
    "escudo",
    "escumadeira",
    "esfigmomanometro",
    "esfregao",
    "esmalte",
    "espada",
    "espanador",
    "esparadrapo",
    "espartilho",
    "espelho",
    "espeto",
    "espingarda",
    "espiral",
    "esponja",
    "espremedor de alho",
    "espremedor de frutas",
    "espatula",
    "esquadro",
    "estabilizador",
    "estaca",
    "estandarte",
    "estante",
    "estatueta do oscar",
    "esteira ergometrica",
    "esterilizador",
    "estetoscopio",
    "estilete",
    "estilingue",
    "estojo",
    "estojo de maquiagem",
    "estribo",
    "estatua",
    "etiqueta",
    "exaustor",
    "extintor de incendio",
    "faca",
    "facao",
    "fagote",
    "faixa",
    "fantasia",
    "fantoche",
    "faqueiro",
    "farda",
    "farinheiro",
    "farol de milha",
    "farolete",
    "fax",
    "ferradura",
    "ferro de passar roupa",
    "ferrolho",
    "ferrorama",
    "fichario",
    "figurinha",
    "filmadora",
    "filtro de linha",
    "filtro de papel",
    "filtro de agua",
    "fio",
    "fio dental",
    "fita",
    "fita adesiva",
    "fita cassete",
    "fita crepe",
    "fita isolante",
    "fivela",
    "flanela",
    "flauta",
    "flecha",
    "flamula",
    "focinheira",
    "foguete",
    "fogao",
    "fogao a lenha",
    "foice",
    "fones de ouvido",
    "forma",
    "forma de gelo",
    "formao",
    "forno",
    "forno eletrico",
    "frangueira",
    "frasco",
    "freezer",
    "frigideira",
    "frigobar",
    "fronha",
    "fruteira",
    "funil",
    "furadeira",
    "fusivel",
    "fuzil",
    "gabinete",
    "gaiola",
    "gaita",
    "galheteiro",
    "galocha",
    "gancho",
    "gangorra",
    "ganza",
    "garafa pet",
    "garfo",
    "gargantilha",
    "garrafa",
    "garrafa pet",
    "garrafa termica",
    "gaveta",
    "geladeira",
    "gesso",
    "gibi",
    "giroflex",
    "giz",
    "giz de cera",
    "gloss",
    "gongo",
    "gorro",
    "gramofone",
    "grampeador",
    "grampo de cabelo",
    "granada",
    "gravata",
    "grelha",
    "grinalda",
    "guarda-chuva",
    "guarda-roupa",
    "guarda-sol",
    "guardanapo",
    "guidao",
    "guilhotina",
    "guindaste",
    "guirlanda",
    "guitarra",
    "haltere",
    "harpa",
    "hidrante",
    "holofote",
    "helice",
    "iate",
    "impressora",
    "incenso",
    "incensario",
    "ingresso",
    "interfone",
    "ioio",
    "isqueiro",
    "jaleco",
    "janela",
    "jangada",
    "jaqueta",
    "jardineira",
    "jarra",
    "jeans",
    "joelheira",
    "jornal",
    "kunai",
    "lacre",
    "lajota",
    "lamparina",
    "lampiao",
    "lancheira",
    "lantejoula",
    "lanterna",
    "lanterna chinesa",
    "lanca",
    "lapiseira",
    "laque",
    "lata",
    "laco",
    "leiteira",
    "lembrete",
    "leme",
    "lente",
    "lente de contato",
    "lenco",
    "lencol",
    "leque",
    "liquidificador",
    "lira",
    "lista telefonica",
    "livro",
    "lixa de unha",
    "lixeira",
    "lona",
    "lousa",
    "luminaria",
    "luneta",
    "lupa",
    "lustre",
    "luva",
    "luva de boxe",
    "lapis",
    "lapis de cor",
    "lapis de olho",
    "lapis labial",
    "lamina",
    "lampada",
    "la de aco",
    "lingua de sogra",
    "maca",
    "macacao",
    "machado",
    "maio",
    "mala",
    "malhete",
    "malote",
    "mamadeira",
    "manequim",
    "manete",
    "mangueira",
    "manivela",
    "manta",
    "mapa",
    "maquete",
    "maraca",
    "marcador de pagina",
    "marcador de texto",
    "marimba",
    "marionete",
    "marreta",
    "martelo",
    "mastro",
    "mata-mosca",
    "macaneta",
    "macarico",
    "medalha",
    "megafone",
    "meia",
    "meia arrastao",
    "meia-calca",
    "mesa",
    "mesa de ping-pong",
    "mesa de sinuca",
    "metralhadora",
    "micro-ondas",
    "microfone",
    "microscopio",
    "mimeografo",
    "minissaia",
    "micanga",
    "mochila",
    "modem",
    "moeda",
    "mola",
    "molheira",
    "molinete",
    "monitor",
    "monoculo",
    "mordaca",
    "mordedor",
    "mosquiteiro",
    "motor",
    "mouse",
    "mouse pad",
    "muleta",
    "multiprocessador",
    "munhequeira",
    "mural",
    "maquina de costura",
    "maquina de datilografar",
    "maquina de lavar louca",
    "maquina de lavar roupa",
    "maquina fotografica",
    "mascara",
    "mascara cirurgica",
    "mascara de mergulho",
    "mascara de oxigenio",
    "missil",
    "narguile",
    "nariz de palhaco",
    "navalha",
    "nebulizador",
    "notebook",
    "novelo de la",
    "oboe",
    "odre",
    "ofuro",
    "olho magico",
    "ombreira",
    "orelhao",
    "origami",
    "pacote",
    "palafita",
    "paleto",
    "palheta",
    "paliteiro",
    "palito de dente",
    "palito de fosforo",
    "palmilha",
    "pandeiro",
    "panela",
    "panela de barro",
    "panela de pressao",
    "panfleto",
    "pano",
    "pano de chao",
    "pano de prato",
    "pantufa",
    "papel",
    "papel carbono",
    "papel higienico",
    "papel laminado",
    "papel toalha",
    "papete",
    "para-raios",
    "parabrisa",
    "parafina",
    "parafuso",
    "paraquedas",
    "parca",
    "pasta",
    "patinete",
    "patins",
    "pato de borracha",
    "pedal",
    "pedra-pomes",
    "pen drive",
    "peneira",
    "penhoar",
    "pente",
    "penteadeira",
    "perfume",
    "perfurador de papel",
    "pergaminho",
    "periscopio",
    "perna de pau",
    "persiana",
    "peruca",
    "peteca",
    "petisqueira",
    "pia",
    "piano",
    "picareta",
    "piercing",
    "pijama",
    "pilha",
    "pilao",
    "pincel",
    "pingente",
    "pino",
    "pinca",
    "pipa",
    "pipeta",
    "pipoqueira",
    "pires",
    "pisca-pisca",
    "pistola",
    "piao",
    "placa",
    "pluma",
    "pneu",
    "pochete",
    "podadeira",
    "polaina",
    "poltrona",
    "poncheira",
    "ponteiro",
    "porta",
    "porta cd",
    "porta-lapis",
    "porta-retrato",
    "poster",
    "pote",
    "prancha",
    "prancheta",
    "prateleira",
    "prato",
    "pregador",
    "prego",
    "prendedor de cabelo",
    "presente",
    "presilha",
    "projetil",
    "protetor auricular",
    "protetor bucal",
    "puff",
    "pulseira",
    "pulverizador",
    "punhal",
    "puxador",
    "pa",
    "pa de lixo",
    "pe de cabra",
    "pe de pato",
    "perola",
    "pendulo",
    "podio",
    "quadro",
    "quebra-cabeca",
    "quebra-nozes",
    "queijeira",
    "quepe",
    "quimono",
    "rabeca",
    "rack",
    "radar",
    "ralador",
    "ralo",
    "ralo de pia",
    "raquete",
    "raquete eletrica",
    "rasteirinha",
    "rastelo",
    "ratoeira",
    "reco-reco",
    "rede",
    "rede de descanso",
    "rede de pesca",
    "refratario",
    "regador",
    "relicario",
    "relogio",
    "relogio de pulso",
    "relogio de sol",
    "remo",
    "retrato",
    "retroprojetor",
    "retrovisor",
    "revista",
    "revisteiro",
    "revolver",
    "rifle",
    "rodape",
    "rodo",
    "rolha",
    "rolo de massa",
    "rosario",
    "roteador",
    "radio",
    "radio amador",
    "radio gravador",
    "redea",
    "regua",
    "rimel",
    "saboneteira",
    "sabre",
    "saca-rolhas",
    "saco de plastico",
    "saia",
    "saladeira",
    "saleiro",
    "salto alto",
    "samba cancao",
    "sanduicheira",
    "sandalia",
    "sanfona",
    "sapateira",
    "sapatilha",
    "sapato",
    "saxofone",
    "scanner",
    "secador de cabelo",
    "secadora",
    "semaforo",
    "seringa",
    "serpentina",
    "serra",
    "serra eletrica",
    "serrote",
    "short",
    "sino",
    "sirene",
    "skate",
    "smoking",
    "soco ingles",
    "sofa",
    "sombrero",
    "sombrinha",
    "sorveteira",
    "spray",
    "sunga",
    "suspensorio",
    "sutia",
    "sueter",
    "tablet",
    "tabuleiro",
    "taco",
    "talco",
    "talher",
    "tamanco",
    "tambor",
    "tamborim",
    "tampa",
    "tanga",
    "tanque",
    "tapete",
    "tatame",
    "taca",
    "tear",
    "tecido",
    "teclado",
    "tela",
    "telefone",
    "telescopio",
    "televisao",
    "telha",
    "termometro",
    "terno",
    "tesoura",
    "tiara",
    "tigela",
    "tijolo",
    "tinta de cabelo",
    "toalha",
    "toalha de mesa",
    "toboga",
    "toga",
    "toldo",
    "torneira",
    "tornozeleira",
    "torpedo",
    "torradeira",
    "touca",
    "trampolim",
    "transferidor",
    "trave",
    "travesseiro",
    "tridente",
    "tripe",
    "triturador",
    "triangulo",
    "trofeu",
    "trombone",
    "trompa",
    "trompete",
    "trono",
    "tuba",
    "tubo de ensaio",
    "tumba",
    "turbante",
    "turbina",
    "tabua",
    "tenis",
    "tunica",
    "unha postica",
    "uniforme",
    "urna",
    "varal",
    "vasilha",
    "vaso",
    "vaso sanitario",
    "vassoura",
    "vela",
    "ventilador",
    "ventilador de teto",
    "vestido",
    "vidro",
    "viola",
    "violino",
    "violoncelo",
    "violao",
    "viseira",
    "vitrola",
    "volante",
    "veu",
    "video cassete",
    "video game",
    "webcam",
    "xilofone",
    "xicara",
    "zabumba",
    "zarabatana",
    "ziper",
    "abaco",
    "album",
    "arvore de natal",
    "ancora",
    "ima",
    "oculos",
    "oculos de sol",
    "orgao",
  ],
};
